# Base de imagen optimizada para Node.js
FROM node:16-alpine AS development

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el archivo package.json y package-lock.json (si existe)
COPY package*.json ./

# Instalar las dependencias, incluyendo las de desarrollo
RUN npm i pnpm -g

RUN pnpm install

# Copiar los archivos de configuración del TypeScript
COPY tsconfig.json ./

# Copiar el código fuente de la aplicación
COPY src ./src

# Puerto en el que se ejecutará la aplicación en modo desarrollo
EXPOSE 3001

# Comando para iniciar la aplicación en modo desarrollo
CMD ["pnpm", "run", "start:dev"]