version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=resources
      - POSTGRES_USER=lucho
      - POSTGRES_PASSWORD =admin123
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data

  pgadmin:
      image: dpage/pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
        - PGADMIN_DEFAULT_PASSWORD=admin
      ports:
        - "5050:80"
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    restart: always
